# Generated by Django 5.0.4 on 2024-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.CharField(default='your name', max_length=100, null=True),
        ),
    ]
