# Generated by Django 5.0.4 on 2024-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_document_pdf_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_bureau',
            field=models.EmailField(default='Office Email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.CharField(default='Function', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Your Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_number',
            field=models.CharField(default='Office Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, default='Website', max_length=500, null=True),
        ),
    ]
