# Generated by Django 5.0.4 on 2024-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress_link',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
