# Generated by Django 5.0.4 on 2024-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_facebook_user_instagram_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.CharField(default='entreprise', max_length=100, null=True),
        ),
    ]
