# Generated by Django 5.0.4 on 2024-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_adress_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_bureau',
            field=models.CharField(default='office Mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_number',
            field=models.CharField(default='office number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='number', max_length=100, null=True),
        ),
    ]
