# Generated by Django 5.0.4 on 2024-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(upload_to='media/PDF/'),
        ),
    ]
